<div style="border:1px solid #CCCCCC;margin-bottom:10px;padding:10px 10px 10px 10px;">
    <h4><?php echo $this->__('About PiroBox Extended (1.0)'); ?></h4>
    <p><?php echo $this->__('PiroBox Extended is advanced form of PiroBox (1.2.2) which has the ability to open any type of file, from inLine content to swf files, likewise, from simple images to pdf files.'); ?><br/>
        <?php echo $this->__('Click <a href="http://www.pirolab.it/pirobox" target="_blank">here</a> for more details'); ?>
    </p>
</div>