<?php
/**
 *
 * @category SunshineBiz
 * @package SocialConnect
 * @author     iSunshineTech <isunshinetech@gmail.com>
 * @copyright   Copyright (c) 2013 SunshineBiz.commerce, Inc. (http://www.sunshinebiz.cn)
 */
?>
<div class="clearer">
    <div class="socialconnect-alipay" onclick="document.getElementById('alipay-href').click();" onmouseover="document.getElementById('alipay-href').focus();" onmouseout="document.getElementById('alipay-href').blur();">
        <div class="socialconnect-alipay-inner">
            <a id="alipay-href" href="<?php echo $this->escapeUrl($this->_getButtonUrl()); ?>"><?php echo $this->_getButtonText(); ?></a>
        </div>
        <div class="socialconnect-alipay-right"></div>
    </div>
</div>
