<?php
/**
 *
 * @category SunshineBiz
 * @package Facebook
 * @author     iSunshineTech <isunshinetech@gmail.com>
 * @copyright   Copyright (c) 2014 SunshineBiz.commerce, Inc. (http://www.sunshinebiz.cn)
 */
?>
<div class="clearer">
    <div class="socialconnect-facebook">
        <div class="socialconnect-facebook-inner">
            <a href="<?php echo $this->escapeUrl($this->_getButtonUrl()); ?>"><?php echo $this->_getButtonText(); ?></a>
        </div>
        <div class="socialconnect-facebook-right"></div>
    </div>
</div>