<?php
/**
 *
 * @category SunshineBiz
 * @package Sales
 * @author     iSunshineTech <isunshinetech@gmail.com>
 * @copyright   Copyright (c) 2014 SunshineBiz.commerce, Inc. (http://www.sunshinebiz.cn)
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h1><?php echo Mage::helper('sales')->__('My Orders') ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if ($_orders->getSize()): ?>
    <table class="data-table" id="my-orders-table">
        <col width="1" />
        <col width="1" />
        <col />
        <col width="1" />
        <col width="1" />
        <col />
        <thead>
            <tr>
                <th><?php echo Mage::helper('sales')->__('Order #') ?></th>
                <th><?php echo Mage::helper('sales')->__('Date') ?></th>
                <th><?php echo Mage::helper('sales')->__('Ship To') ?></th>
                <th><span class="nobr"><?php echo Mage::helper('sales')->__('Order Total') ?></span></th>
                <th><span class="nobr"><?php echo Mage::helper('sales')->__('Order Status') ?></span></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php $_odd = ''; ?>
            <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td><?php echo $_order->getRealOrderId() ?></td>
                    <td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                    <td><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td><em><?php echo $_order->getStatusLabel() ?></em></td>
                    <td class="a-center">
                        <span class="nobr"><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo Mage::helper('sales')->__('View Order') ?></a>
                            <?php if (($payUrl = $this->getPayUrl($_order))) : ?>
                                <span class="separator">|</span> <a href="<?php echo $payUrl ?>"><?php echo $this->__('Pay') ?></a>
                            <?php endif ?>
                            <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                                <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo Mage::helper('sales')->__('Reorder') ?></a>
                            <?php endif ?>
                        </span>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-orders-table');</script>
    <?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo Mage::helper('sales')->__('You have placed no orders.'); ?></p>
<?php endif ?>
