<?php
/**
 *
 * @category SunshineBiz
 * @package SocialConnect
 * @author     iSunshineTech <isunshinetech@gmail.com>
 * @copyright   Copyright (c) 2013 SunshineBiz.commerce, Inc. (http://www.sunshinebiz.cn)
 */
?>
<div class="clearer">
    <div class="socialconnect-twitter">
        <div class="socialconnect-twitter-inner">
            <a href="<?php echo $this->escapeUrl($this->_getButtonUrl()); ?>"><?php echo $this->_getButtonText(); ?></a>
        </div>
        <div class="socialconnect-twitter-right"></div>
    </div>
</div>