<script type="text/javascript">
<!--
<?php $myBlock = $this->getLayout()->getBlock('user.roles.grid'); ?>
<?php if( is_object($myBlock) && $myBlock->getJsObjectName() ): ?>
    var checkBoxes = $H(<?php echo $myBlock->_getSelectedRoles(true) ?>);
    var warning = false;
    if (checkBoxes.size() > 0) {
        warning = true;
    }
    $('user_user_roles').value = checkBoxes.toQueryString();

    function registerUserRole(grid, element, checked)
    {
        if (checked) {
            checkBoxes.set(element.value, 0);
        } else {
            checkBoxes.unset(element.value);
        }
        $('user_user_roles').value = checkBoxes.toQueryString();
        grid.reloadParams = {'user_user_roles[]':checkBoxes.keys()};
    }

    function roleUsersRowClick(grid, event)
    {
        var trElement = Event.findElement(event, 'tr');
        var isInput   = Event.element(event).tagName === 'INPUT';
        if (trElement) {
            var checkbox = Element.getElementsBySelector(trElement, 'input');
            if(checkbox[0]){
                var checked = isInput ? !checkbox[0].checked : checkbox[0].checked;
                var flag = false;
                if (checked) {
                    if ( confirm("<?php echo $this->__('Warning!\r\nThis action will remove this user from already assigned role\r\nAre you sure?') ?>") ) {
                        checkbox[0].checked = false;
                        checkBoxes.unset(checkbox[0].value);
                        varienElementMethods.setHasChanges(checkbox[0]);
                        flag = true;
                    } else {
                        checkbox[0].checked = true;
                    }
                } else {
                    checkbox[0].checked = true;
                    checkBoxes.set(checkbox[0].value, true);
                    flag = true;
                }

                $('user_user_roles').value = checkBoxes.toQueryString();
                grid.reloadParams = {'user_user_roles[]':checkBoxes.keys()};
                if(flag)
                    rolesChanged();
            }
        }
    }

    function roleUsersRowInit(grid, row)
    {
        var checkbox = $(row).getElementsByClassName('checkbox')[0];
        if (checkbox) {
            if (checkbox.checked) {
                checkBoxes.set(checkbox.value, checkbox.checked);
            } else {
                checkBoxes.unset(checkbox.value);
            }

            $('user_user_roles').value = checkBoxes.toQueryString();
            grid.reloadParams = {'user_user_roles[]':checkBoxes.keys()};
        }
    }
    
<?php echo $myBlock->getJsObjectName() ?>.rowClickCallback = roleUsersRowClick;
<?php echo $myBlock->getJsObjectName() ?>.initRowCallback = roleUsersRowInit;
<?php echo $myBlock->getJsObjectName() ?>.checkboxCheckCallback = registerUserRole;
<?php echo $myBlock->getJsObjectName() ?>.rows.each(function(row){roleUsersRowInit(<?php echo $myBlock->getJsObjectName() ?>, row)});
    $('user_user_roles_old').value = $('user_user_roles').value;
<?php endif; ?>
//-->
</script>