<?php
/**
 *
 * @category SunshineBiz
 * @package Catalog
 * @author     iSunshineTech <isunshinetech@gmail.com>
 * @copyright   Copyright (c) 2014 SunshineBiz.commerce, Inc. (http://www.sunshinebiz.cn)
 */
?>

<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="page-title category-title">
    <h1><?php echo $this->getTitle(); ?></h1>
</div>
<?php if($this->getMode() =='list'): ?>
<?php 
    $_iterator = 0;
    $_helper = $this->helper('catalog/output');
?>
<ol class="products-list" id="products-list">
<?php foreach ($_products->getItems() as $_product): ?>
    <li class="item<?php if( ++$_iterator == sizeof($_products) ): ?> last<?php endif; ?>">
        <?php // Product Image ?>
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
        <?php // Product description ?>
        <div class="product-shop">
            <div class="f-fix">
                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product) ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <?php if($_product->isSaleable()): ?>
                    <p><button type="button" title="<?php echo Mage::helper('catalog')->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo Mage::helper('catalog')->__('Add to Cart') ?></span></span></button></p>
                <?php else: ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
                <div class="desc std">
                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                </div>
                <ul class="add-to-links">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo Mage::helper('catalog')->__('Add to Wishlist') ?></a></li>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo Mage::helper('catalog')->__('Add to Compare') ?></a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </li>
<?php endforeach; ?>
</ol>
<?php else: ?>
<?php if($this->getMode() == 'grid'): ?>
<?php $_columnCount = $this->getColumnCount(); ?>
<?php else: ?>
<ul class="jcarousel-skin-tango<?php if($this->getMode() == 'slider-horiz'): ?> horiz<?php endif; ?><?php if($this->getMode() == 'slider-verti'): ?> verti<?php endif; ?><?php if($this->getMode() != 'sidebar-list'): ?> products-grid<?php endif; ?>">
<?php endif; ?>
<?php $i=0; foreach ($_products->getItems() as $_product): ?>
<?php if($this->getMode() == 'grid'): ?>
<?php if ($i++%$_columnCount==0): ?>
<ul class="products-grid">    
<?php endif ?>
    <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
<?php else: ?>
    <li<?php if($this->getMode() != 'slider-verti' && $this->getMode() != 'slider-horiz'): ?> class="item"<?php endif ?>>
<?php endif ?>
        <?php if($this->getMode() == 'slider-verti' || $this->getMode() == 'slider-horiz'): ?>
        <div class="boxgrid caption">
        <?php endif ?>
            <p class="product-image">
                <a href="<?php echo $this->getUrl('catalog/product/quickview/id/' . $_product->getId()) ?>" rel="nofollow" title="<?php echo $this->escapeHtml($_product->getName()) ?>" class="ajax"><?php echo $this->__('Quick View') ?></a>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135) ?>" width="135" height="135" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" /></a>
            </p>
        <?php if($this->getMode() == 'slider-verti' || $this->getMode() == 'slider-horiz'): ?>
        <div class="cover boxcaption">
        <?php endif ?>
        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a></h3>
        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
        <?php echo $this->getPriceHtml($_product, true) ?>
        <div<?php if($this->getMode() != 'slider-verti' && $this->getMode() != 'slider-horiz'): ?> class="actions"<?php endif;?>>
            <?php if($_product->isSaleable()): ?>
            <button type="button" title="<?php echo Mage::helper('catalog')->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo Mage::helper('catalog')->__('Add to Cart') ?></span></span></button>
            <?php else: ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
            <p>
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo Mage::helper('catalog')->__('Add to Wishlist') ?></a>
                <?php endif; ?>
                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                <span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo Mage::helper('catalog')->__('Add to Compare') ?></a>
                <?php endif; ?>
            </p>
        </div>
        <?php if($this->getMode() == 'slider-verti' || $this->getMode() == 'slider-horiz'): ?>
        </div>
        </div>
        <?php endif ?>
    </li>
<?php if($this->getMode() =='grid'): ?>
<?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
</ul>
<?php endif ?>
<?php endif ?>
<?php endforeach; ?>
<?php if($this->getMode() !='grid'): ?>
</ul>
<script type="text/javascript">
    Event.observe(window, 'load', function() {
        new ProductInfo('.ajax', 'p.product-image a', {
            'loader': "<?php echo $this->getSkinUrl('images/sunshinebiz/catalog/ajax_loader.gif')?>",
            'loadingMessage': "<?php echo $this->__('Loading') ?>"
        });
    });
</script>
<?php endif; ?>
<?php endif; ?>
<?php endif; ?>