<div style="border:1px solid #CCCCCC;margin-bottom:10px;padding:10px 10px 10px 10px;">
    <h4><?php echo $this->__('About LightboxClone (0.5)'); ?></h4>
    <p><?php echo $this->__('jQuery lightBox plugin is simple, elegant, unobtrusive, no need extra markup and is used to overlay images on the current page through the power and flexibility of jQuery\'s selector.'); ?><br />
        <?php echo $this->__('Click <a href="http://leandrovieira.com/projects/jquery/lightbox/" target="_blank">here</a> for more details'); ?>
    </p>
</div>