<div style="border:1px solid #CCCCCC;margin-bottom:10px;padding:10px 10px 10px 10px;">
    <h4><?php echo $this->__('About PiroBox (1.2.2)'); ?></h4>
    <p><?php echo $this->__('PiroBox is yet another cool jQuery LightBox plugin.'); ?><br /><br />
        <?php echo $this->__('Currently it\'s further development is carried under the name of <strong>PiroBox Extended</strong>.'); ?>
    </p>
</div>