<?php
/**
 *
 * @category SunshineBiz
 * @package SocialConnect
 * @author     iSunshineTech <isunshinetech@gmail.com>
 * @copyright   Copyright (c) 2014 SunshineBiz.commerce, Inc. (http://www.sunshinebiz.cn)
 */
?>
<?php $_code = $this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <img src="<?php echo $this->getSkinUrl('sunshinebiz/alipay/pay/images/alipay.jpg'); ?>" alt="<?php echo $this->__('alipay') ?>" />
    </li>
    <li>
        <p><?php echo $this->__('You will be redirected to Alipay website when you pay an order.') ?></p>
    </li>
</ul>