<div style="border:1px solid #CCCCCC;margin-bottom:10px;padding:10px 10px 10px 10px;">
    <h4><?php echo $this->__('About prettyPhoto (3.1.3)'); ?></h4>
    <p><?php echo $this->__('prettyPhoto is a jQuery lightbox clone. Not only does it support images, it also support for videos, flash, YouTube, iframes and ajax. It\'s a full blown media lightbox.'); ?><br/>
        <?php echo $this->__('Click here for more details: <a href="http://www.no-margin-for-errors.com/projects/prettyphoto-jquery-lightbox-clone/" target="_blank">Homepage</a> | <a href="http://www.no-margin-for-errors.com/projects/prettyphoto-jquery-lightbox-clone/documentation/" target="_blank">Documentation</a>'); ?>
    </p>
</div>