<?php
/**
 *
 * @category SunshineBiz
 * @package Twitter
 * @author     iSunshineTech <isunshinetech@gmail.com>
 * @copyright   Copyright (c) 2014 SunshineBiz.commerce, Inc. (http://www.sunshinebiz.cn)
 */
?>
<div class="clearer">
    <div class="socialconnect-twitter" onclick="document.getElementById('twitter-href').click();" onmouseover="document.getElementById('twitter-href').focus();" onmouseout="document.getElementById('twitter-href').blur();">
        <div class="socialconnect-twitter-inner">
            <a id="twitter-href" href="<?php echo $this->escapeUrl($this->_getButtonUrl()); ?>"><?php echo $this->_getButtonText(); ?></a>
        </div>
        <div class="socialconnect-twitter-right"></div>
    </div>
</div>