<div style="border:1px solid #CCCCCC;margin-bottom:10px;padding:10px 10px 10px 10px;">
    <h4><?php echo $this->__('About FancyBox (1.3.4)'); ?></h4>
    <p><?php echo $this->__('FancyBox is a tool for displaying images, html content and multi-media in a Mac-style "lightbox" that floats overtop of web page.'); ?><br/>
        <?php echo $this->__('For more details visit the links: <a href="http://fancybox.net/home" target="_blank">Homepage</a> | <a href="http://fancybox.net/api" target="_blank">Configuration Options</a>'); ?>
    </p>
</div>